### ISSUE TITLE
Issues after upgrade to 0.90.2

### ISSUE THREAD

**Issue by DoubleAmperSand** [scottyphillips/mitsubishi_echonet#2] opened 2019-03-30 07:51 UTC
Hi 
I Upgraded to HA 0.90.2 today and now the component doesn't work.
I've tried removing it and re adding it but not luck 
all i get in the log is : 2019-03-30 07:45:32 WARNING (MainThread) [homeassistant.loader] You are using a custom component for mitsubishi.climate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

**Comment by scottyphillips** [comment] 2019-04-11 21:42
Hi @DoubleAmperSand, I am aware that HA changed the way they handle custom components from version 0.89 onwards, unfortunately I had not had an opportunity until today to look at the problem in depth. I did update the custom component based upon feedback in the HA forums so maybe try to pull the updated version and give that a go. The library itself should not be impacted only the HA component. I should have my own environment updated in a few days to version 0.91 so I will be able to sort it out.

**Comment by scottyphillips** [comment] 2019-04-12 10:32
Hi @DoubleAmperSand I have upgraded my own environment today and refreshed the HA code in the examples section. As per the new custom components requirements I have renamed 'mitsubishi.py' to 'climate.py' and instead of placing into a 'climate' folder it goes into a 'mitsubishi' folder. The updated code has the file path you need. Can you pull it and try it out? 

v0.90 seems to be painful with managing python dependancies for custom components (at least for me) so let me know if you have any other errors.

**Comment by scottyphillips** [comment] 2019-05-04 04:23
Closing issue as custom component is confirmed working as of version 0.92

**Closed as completed by scottyphillips** 2019-05-04 04:23 UTC
Labels: bug
